import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Github, X, Check, FolderSearch, FileText, RefreshCw, Terminal, Command } from 'lucide-react';
import { projects, type Project } from '../data/projects';
import { githubUrl } from '../data/profile';
import { Heading, Reveal, ExternalLink } from './UI';
import ProjectCard from './ProjectCard';
export default function Projects() { const [selected, setSelected] = useState<Project | null>(null); const dialog = useRef<HTMLDialogElement>(null); useEffect(() => { if (selected) {
    dialog.current?.showModal();
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => { document.body.style.overflow = prev; dialog.current?.close(); };
} }, [selected]); return <section id="projetos" className="section container"><Reveal><Heading number="03" eyebrow="IDEIAS QUE VIRARAM CÓDIGO" title="Projetos" description="Construídos a partir de problemas reais. Pensados para quem usa."/><article className="featured"><div className="featured-copy"><span className="eyebrow">FEATURED PROJECT <span className="blue">/ 01</span></span><h3>NexIT<span>.</span></h3><h4>Internal IT Platform</h4><p>Uma plataforma criada para centralizar ferramentas, procedimentos e automações utilizadas no setor de tecnologia.</p><div className="tags">{projects[0].tech.map(t => <span key={t}>{t}</span>)}</div><div className="actions"><button className="button primary" onClick={() => setSelected(projects[0])}>Detalhes <ArrowUpRight size={18}/></button><ExternalLink href={projects[0].github} className="button secondary" label="GitHub do NexIT"><Github size={18}/> GitHub</ExternalLink></div></div><div className="app-preview" aria-label="Ilustração conceitual dos módulos do NexIT"><div className="window-bar"><div className="window-dots"><i /><i /><i /></div><span>NexIT / workspace</span><Command size={14}/></div><div className="app-content"><div className="app-sidebar"><Terminal size={20}/><FileText size={18}/><FolderSearch size={18}/><RefreshCw size={18}/></div><div className="app-main"><div className="app-breadcrumb">workspace <span>/ visão geral</span></div><h4>Seu próximo passo,<br />mais simples.</h4><p>Ferramentas que trabalham com você.</p><div className="app-modules">{[[FileText, 'Procedimentos'], [FolderSearch, 'Busca de arquivos'], [RefreshCw, 'Conversão de mídia'], [Terminal, 'Automações']].map(([Icon, label]) => { const I = Icon as typeof Terminal; return <div key={String(label)}><I size={18}/><span>{String(label)}</span></div>; })}</div><small>VISÃO CONCEITUAL DA PLATAFORMA</small></div></div></div></article><div className="project-grid">{projects.map((p, i) => <ProjectCard key={p.id} project={p} index={i} onSelect={setSelected}/>)}</div><div className="all-projects"><ExternalLink href={githubUrl ? `${githubUrl}?tab=repositories` : ''} label="Todos os projetos no GitHub">Ver todos os projetos no GitHub <ArrowUpRight size={17}/></ExternalLink></div></Reveal><dialog ref={dialog} onCancel={() => setSelected(null)} onClick={e => { if (e.target === dialog.current)
    setSelected(null); }} onClose={() => setSelected(null)} aria-labelledby="project-title"><div className="dialog-content"><button className="dialog-close" aria-label="Fechar detalhes" onClick={() => setSelected(null)}><X /></button>{selected && <><span className="eyebrow">{selected.category}</span><h2 id="project-title">{selected.name}</h2><p>{selected.description}</p><h3>O que o projeto reúne</h3><ul className="feature-list">{selected.features.map(f => <li key={f}><Check size={17}/>{f}</li>)}</ul><div className="tags">{selected.tech.map(t => <span key={t}>{t}</span>)}</div><p className="muted">{selected.status}{!selected.github && !selected.url ? ' · Acesso público não informado.' : ''}</p>{(selected.github || selected.url) && <div className="actions">{selected.github && <ExternalLink href={selected.github} className="button secondary">GitHub <Github size={18}/></ExternalLink>}{selected.url && <ExternalLink href={selected.url} className="button primary">Abrir aplicação <ArrowUpRight size={18}/></ExternalLink>}</div>}</>}</div></dialog></section>; }
